### ISSUE TITLE
Small screen sizes: page scrolled to bottom by default

### ISSUE THREAD

**Issue by dominikbraun** [aligator/dev#2]
When using a smaller screen, the page is scrolled to the bottom by default.

**Expected:**

<img width="741" alt="Screenshot 2021-04-10 at 09 37 52" src="https://user-images.githubusercontent.com/36575275/114262511-a8e16580-99e0-11eb-9a96-526926a13200.png">

**Actual:**

<img width="741" alt="Screenshot 2021-04-10 at 09 37 39" src="https://user-images.githubusercontent.com/36575275/114262518-aed74680-99e0-11eb-89ef-a9a060fd576f.png">

**Comment by aligator** [comment]
The window now has initially a size which adapts to the screen size. That way it should be a better experience on small screens.
Not perfect, but better...
